## Summary statistics and missing value report
## df.describe() on all numeric columns, df.isna().sum(), and list any column with >5% nulls.

In [64]:
import pandas as pd

In [65]:
df = pd.read_csv("../data/benin/raw/benin-malanville.csv")

#thd rows and columns of the dataframe
print(f"Shape (rows, columns): {df.shape}\n")

#the data type of each column
print("Column dtypes:")
print(df.dtypes, "\n")

# Null counts and columns with >5% nulls
na_counts = df.isna().sum()
print("Null counts per column:")
print(na_counts)

percent_null = (na_counts / len(df)) * 100
print("\nNull percentage per column:")
print(percent_null.round(2))

cols_over_5pct = percent_null[percent_null > 5].sort_values(ascending=False)
if not cols_over_5pct.empty:
    print("\nColumns with >5% nulls:")
    for col, pct in cols_over_5pct.items():
        print(f"- {col}: {pct:.2f}% ({na_counts[col]} nulls)")
else:
    print("\nNo columns with >5% nulls.")

#descsriptive statistics
print("\nDescriptive statistics (numeric):")
display(df.describe())
print("\nDescriptive statistics (all columns):")
display(df.describe(include='all'))

Shape (rows, columns): (525600, 19)

Column dtypes:
Timestamp         object
GHI              float64
DNI              float64
DHI              float64
ModA             float64
ModB             float64
Tamb             float64
RH               float64
WS               float64
WSgust           float64
WSstdev          float64
WD               float64
WDstdev          float64
BP                 int64
Cleaning           int64
Precipitation    float64
TModA            float64
TModB            float64
Comments         float64
dtype: object

Null counts per column:
Timestamp             0
GHI                   0
DNI                   0
DHI                   0
ModA                  0
ModB                  0
Tamb                  0
RH                    0
WS                    0
WSgust                0
WSstdev               0
WD                    0
WDstdev               0
BP                    0
Cleaning              0
Precipitation         0
TModA                 0
TModB                 0
Comments         525600
dtype: int64

Null percentage per column:
Timestamp          0.0
GHI                0.0
DNI                0.0
DHI                0.0
ModA               0.0
ModB               0.0
Tamb               0.0
RH                 0.0
WS                 0.0
WSgust             0.0
WSstdev            0.0
WD                 0.0
WDstdev            0.0
BP                 0.0
Cleaning           0.0
Precipitation      0.0
TModA              0.0
TModB              0.0
Comments         100.0
dtype: float64

Columns with >5% nulls:
- Comments: 100.00% (525600 nulls)

Descriptive statistics (numeric):

,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,Comments
count,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,0.0
mean,240.559452,167.187516,115.358961,236.589496,228.883576,28.179683,54.487969,2.121113,2.809195,0.473390,153.435172,8.582407,994.197199,0.000923,0.001905,35.246026,32.471736,NaN
std,331.131327,261.710501,158.691074,326.894859,316.536515,5.924297,28.073069,1.603466,2.029120,0.273395,102.332842,6.385864,2.474993,0.030363,0.037115,14.807258,12.348743,NaN
min,-12.900000,-7.800000,-12.600000,0.000000,0.000000,11.000000,2.100000,0.000000,0.000000,0.000000,0.000000,0.000000,985.000000,0.000000,0.000000,9.000000,8.100000,NaN
25%,-2.000000,-0.500000,-2.100000,0.000000,0.000000,24.200000,28.800000,1.000000,1.300000,0.400000,59.000000,3.700000,993.000000,0.000000,0.000000,24.200000,23.600000,NaN
50%,1.800000,-0.100000,1.600000,4.500000,4.300000,28.000000,55.100000,1.900000,2.600000,0.500000,181.000000,8.600000,994.000000,0.000000,0.000000,30.000000,28.900000,NaN
75%,483.400000,314.200000,216.300000,463.700000,447.900000,32.300000,80.100000,3.100000,4.100000,0.600000,235.100000,12.300000,996.000000,0.000000,0.000000,46.900000,41.500000,NaN
max,1413.000000,952.300000,759.200000,1342.300000,1342.300000,43.800000,100.000000,19.500000,26.600000,4.200000,360.000000,99.400000,1003.000000,1.000000,2.500000,81.000000,72.500000,NaN

Descriptive statistics (all columns):

,Timestamp,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,Comments
count,525600,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,0.0
unique,525600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2021-08-09 00:01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,240.559452,167.187516,115.358961,236.589496,228.883576,28.179683,54.487969,2.121113,2.809195,0.473390,153.435172,8.582407,994.197199,0.000923,0.001905,35.246026,32.471736,NaN
std,NaN,331.131327,261.710501,158.691074,326.894859,316.536515,5.924297,28.073069,1.603466,2.029120,0.273395,102.332842,6.385864,2.474993,0.030363,0.037115,14.807258,12.348743,NaN
min,NaN,-12.900000,-7.800000,-12.600000,0.000000,0.000000,11.000000,2.100000,0.000000,0.000000,0.000000,0.000000,0.000000,985.000000,0.000000,0.000000,9.000000,8.100000,NaN
25%,NaN,-2.000000,-0.500000,-2.100000,0.000000,0.000000,24.200000,28.800000,1.000000,1.300000,0.400000,59.000000,3.700000,993.000000,0.000000,0.000000,24.200000,23.600000,NaN
50%,NaN,1.800000,-0.100000,1.600000,4.500000,4.300000,28.000000,55.100000,1.900000,2.600000,0.500000,181.000000,8.600000,994.000000,0.000000,0.000000,30.000000,28.900000,NaN
75%,NaN,483.400000,314.200000,216.300000,463.700000,447.900000,32.300000,80.100000,3.100000,4.100000,0.600000,235.100000,12.300000,996.000000,0.000000,0.000000,46.900000,41.500000,NaN
max,NaN,1413.000000,952.300000,759.200000,1342.300000,1342.300000,43.800000,100.000000,19.500000,26.600000,4.200000,360.000000,99.400000,1003.000000,1.000000,2.500000,81.000000,72.500000,NaN

# Outlier detection and basic cleaning

## Data type conversion: fix the date column to proper datetime format

In [68]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'], errors='coerce')
#check the column data types 
print("Column dtypes:")
print(df.dtypes, "\n")

Column dtypes:
Timestamp        datetime64[ns]
GHI                     float64
DNI                     float64
DHI                     float64
ModA                    float64
ModB                    float64
Tamb                    float64
RH                      float64
WS                      float64
WSgust                  float64
WSstdev                 float64
WD                      float64
WDstdev                 float64
BP                        int64
Cleaning                  int64
Precipitation           float64
TModA                   float64
TModB                   float64
Comments                float64
dtype: object

## Catching any missing values- empty strings, 'NA', -999 sentinels

In [69]:
# replace any blank or empty strings with NaN
df.replace({r'^\s*$': pd.NA, r'(?i)^NA$': pd.NA}, regex=True, inplace=True)
# replace numeric sentinels
df.replace([-999, -999.0], pd.NA, inplace=True)
print("\nAfter replacing sentinels and blanks with NaN:")
na_counts_after = df.isna().sum()
print(na_counts_after)

After replacing sentinels and blanks with NaN:
Timestamp             0
GHI                   0
DNI                   0
DHI                   0
ModA                  0
ModB                  0
Tamb                  0
RH                    0
WS                    0
WSgust                0
WSstdev               0
WD                    0
WDstdev               0
BP                    0
Cleaning              0
Precipitation         0
TModA                 0
TModB                 0
Comments         525600
dtype: int64

## Remove any incorrect entries based on domain knowledge

In [79]:
#check for negative values in GHI, DNI, DHI since irradiance should be non-negative
cols = ['GHI', 'DNI', 'DHI']
neg_counts = (df[cols] < 0).sum()
neg_pct = (neg_counts / len(df) * 100).round(2)
print("Negative counts and percentage (of total rows):")
for c in cols:
    print(f"- {c}: {neg_counts[c]} ({neg_pct[c]}%)")
print("total negatives:", neg_counts.sum())

#find the hours when negatives occur
for col in cols:
    mask = df[col] < 0
    if mask.any():
        neg_hours = df.loc[mask, 'Timestamp'].dt.hour.value_counts().sort_index()
        print(f"- negatives by hour count for {col} negatives: timestamp={neg_hours}")
    else:
        print(f"- no negatives for {col}")

Negative counts and percentage (of total rows):
- GHI: 258847 (49.25%)
- DNI: 275987 (52.51%)
- DHI: 259182 (49.31%)
total negatives: 794016
- negatives by hour count for GHI negatives: timestamp=Timestamp
0     21874
1     21900
2     21793
3     21786
4     21870
5     21876
6     14251
7       696
8        33
9         2
15       11
16        8
17       42
18     4879
19    20345
20    21892
21    21839
22    21854
23    21896
Name: count, dtype: int64
- negatives by hour count for DNI negatives: timestamp=Timestamp
0     21641
1     21620
2     21572
3     21536
4     21498
5     21521
6     18995
7      3782
8       414
9       358
10      207
11      128
12      206
13      157
14      144
15      273
16      332
17     1095
18    11520
19    21803
20    21846
21    21831
22    21805
23    21703
Name: count, dtype: int64
- negatives by hour count for DHI negatives: timestamp=Timestamp
0     21884
1     21885
2     21685
3     21770
4     21839
5     21869
6     14349
7       865
8        28
9         2
15       10
16        7
17       65
18     5075
19    20335
20    21885
21    21862
22    21869
23    21898
Name: count, dtype: int64

In [85]:
# replace all negative values in GHI, DNI, DHI with 0
df['GHI'] = df['GHI'].clip(lower=0)
df['DNI'] = df['DNI'].clip(lower=0) 
df['DHI'] = df['DHI'].clip(lower=0)
print("total negatives after clipping to 0:", (df[cols] < 0).sum().sum())
df.describe()

total negatives after clipping to 0: 0

,Timestamp,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,Comments
count,525600,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,0.0
mean,2022-02-07 12:00:30.000000512,241.958821,167.441866,116.993033,236.589496,228.883576,28.179683,54.487969,2.121113,2.809195,0.473390,153.435172,8.582407,994.197199,0.000923,0.001905,35.246026,32.471736,NaN
min,2021-08-09 00:01:00,0.000000,0.000000,0.000000,0.000000,0.000000,11.000000,2.100000,0.000000,0.000000,0.000000,0.000000,0.000000,985.000000,0.000000,0.000000,9.000000,8.100000,NaN
25%,2021-11-08 06:00:45,0.000000,0.000000,0.000000,0.000000,0.000000,24.200000,28.800000,1.000000,1.300000,0.400000,59.000000,3.700000,993.000000,0.000000,0.000000,24.200000,23.600000,NaN
50%,2022-02-07 12:00:30,1.800000,0.000000,1.600000,4.500000,4.300000,28.000000,55.100000,1.900000,2.600000,0.500000,181.000000,8.600000,994.000000,0.000000,0.000000,30.000000,28.900000,NaN
75%,2022-05-09 18:00:15,483.400000,314.200000,216.300000,463.700000,447.900000,32.300000,80.100000,3.100000,4.100000,0.600000,235.100000,12.300000,996.000000,0.000000,0.000000,46.900000,41.500000,NaN
max,2022-08-09 00:00:00,1413.000000,952.300000,759.200000,1342.300000,1342.300000,43.800000,100.000000,19.500000,26.600000,4.200000,360.000000,99.400000,1003.000000,1.000000,2.500000,81.000000,72.500000,NaN
std,NaN,330.101787,261.547532,157.463619,326.894859,316.536515,5.924297,28.073069,1.603466,2.029120,0.273395,102.332842,6.385864,2.474993,0.030363,0.037115,14.807258,12.348743,NaN